In [1]:
import pandas as pd

df = pd.read_csv("ecommerce_dataset.csv")

In [2]:
df.head()

,customer_id,first_name,last_name,gender,age_group,signup_date,country,product_id,product_name,category,quantity,unit_price,order_id,order_date,order_status,payment_method,rating,review_text,review_id,review_date
0,CUST2353,Erica,Oliver,Female,Teenagers,29-06-2022,Canada,PROD108,Fitbit Versa 3,Electronics,3,229,ORD10000,13-07-2023,Pending,Credit Card,2,good,REV20000,06-06-2025
1,CUST4463,Christopher,White,Male,Adults,24-08-2023,China,PROD103,Levi's Jeans,Apparel,4,59,ORD10001,12-08-2024,Pending,PayPal,2,average,REV20001,05-08-2023
2,CUST4512,Spencer,Foster,Male,Senior,18-07-2023,Germany,PROD111,Lego Star Wars Set,Toys,2,59,ORD10002,04-08-2024,Delivered,Cash on Delivery,5,good,REV20002,03-01-2023
3,CUST5711,Jessica,Harris,Male,Teenagers,22-08-2025,France,PROD107,Dyson Vacuum,Home & Kitchen,4,399,ORD10003,23-05-2025,Delivered,Cash on Delivery,2,very good,REV20003,14-03-2023
4,CUST1296,Amy,Johnson,Female,Teenagers,23-03-2021,Brazil,PROD105,Adidas Running Shoes,Apparel,1,110,ORD10004,02-07-2023,Returned,Cash on Delivery,1,very good,REV20004,18-10-2023

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     10000 non-null  object
 1   first_name      10000 non-null  object
 2   last_name       10000 non-null  object
 3   gender          10000 non-null  object
 4   age_group       10000 non-null  object
 5   signup_date     10000 non-null  object
 6   country         10000 non-null  object
 7   product_id      10000 non-null  object
 8   product_name    10000 non-null  object
 9   category        10000 non-null  object
 10  quantity        10000 non-null  int64
 11  unit_price      10000 non-null  int64
 12  order_id        10000 non-null  object
 13  order_date      10000 non-null  object
 14  order_status    10000 non-null  object
 15  payment_method  10000 non-null  object
 16  rating          10000 non-null  int64
 17  review_text     10000 non-null  object
 18  review_id       10000 non-null  object
 19  review_date     10000 non-null  object
dtypes: int64(3), object(17)
memory usage: 1.5+ MB

In [4]:
df.describe()

           quantity    unit_price        rating
count  10000.000000  10000.000000  10000.000000
mean       3.000800    246.647200      2.993100
std        1.416474    282.605391      1.410621
min        1.000000     25.000000      1.000000
25%        2.000000     80.000000      2.000000
50%        3.000000    129.000000      3.000000
75%        4.000000    229.000000      4.000000
max        5.000000    999.000000      5.000000

In [5]:
print(df.isnull().sum())

customer_id       0
first_name        0
last_name         0
gender            0
age_group         0
signup_date       0
country           0
product_id        0
product_name      0
category          0
quantity          0
unit_price        0
order_id          0
order_date        0
order_status      0
payment_method    0
rating            0
review_text       0
review_id         0
review_date       0
dtype: int64

In [6]:
df[df.duplicated(keep='first')]

Empty DataFrame
Columns: [customer_id, first_name, last_name, gender, age_group, signup_date, country, product_id, product_name, category, quantity, unit_price, order_id, order_date, order_status, payment_method, rating, review_text, review_id, review_date]
Index: []

In [7]:
df['full_name'] = df['first_name'] + ' ' + df['last_name']
display(df.head())

,customer_id,first_name,last_name,gender,age_group,signup_date,country,product_id,product_name,category,...,unit_price,order_id,order_date,order_status,payment_method,rating,review_text,review_id,review_date,full_name
0,CUST2353,Erica,Oliver,Female,Teenagers,29-06-2022,Canada,PROD108,Fitbit Versa 3,Electronics,...,229,ORD10000,13-07-2023,Pending,Credit Card,2,good,REV20000,06-06-2025,Erica Oliver
1,CUST4463,Christopher,White,Male,Adults,24-08-2023,China,PROD103,Levi's Jeans,Apparel,...,59,ORD10001,12-08-2024,Pending,PayPal,2,average,REV20001,05-08-2023,Christopher White
2,CUST4512,Spencer,Foster,Male,Senior,18-07-2023,Germany,PROD111,Lego Star Wars Set,Toys,...,59,ORD10002,04-08-2024,Delivered,Cash on Delivery,5,good,REV20002,03-01-2023,Spencer Foster
3,CUST5711,Jessica,Harris,Male,Teenagers,22-08-2025,France,PROD107,Dyson Vacuum,Home & Kitchen,...,399,ORD10003,23-05-2025,Delivered,Cash on Delivery,2,very good,REV20003,14-03-2023,Jessica Harris
4,CUST1296,Amy,Johnson,Female,Teenagers,23-03-2021,Brazil,PROD105,Adidas Running Shoes,Apparel,...,110,ORD10004,02-07-2023,Returned,Cash on Delivery,1,very good,REV20004,18-10-2023,Amy Johnson

In [8]:
columns = df.columns.tolist()
columns.remove('first_name')
columns.remove('last_name')
columns.insert(1, columns.pop(columns.index('full_name'))) # Move 'full_name' after 'customer_id'
df = df[columns]
display(df.head())

,customer_id,full_name,gender,age_group,signup_date,country,product_id,product_name,category,quantity,unit_price,order_id,order_date,order_status,payment_method,rating,review_text,review_id,review_date
0,CUST2353,Erica Oliver,Female,Teenagers,29-06-2022,Canada,PROD108,Fitbit Versa 3,Electronics,3,229,ORD10000,13-07-2023,Pending,Credit Card,2,good,REV20000,06-06-2025
1,CUST4463,Christopher White,Male,Adults,24-08-2023,China,PROD103,Levi's Jeans,Apparel,4,59,ORD10001,12-08-2024,Pending,PayPal,2,average,REV20001,05-08-2023
2,CUST4512,Spencer Foster,Male,Senior,18-07-2023,Germany,PROD111,Lego Star Wars Set,Toys,2,59,ORD10002,04-08-2024,Delivered,Cash on Delivery,5,good,REV20002,03-01-2023
3,CUST5711,Jessica Harris,Male,Teenagers,22-08-2025,France,PROD107,Dyson Vacuum,Home & Kitchen,4,399,ORD10003,23-05-2025,Delivered,Cash on Delivery,2,very good,REV20003,14-03-2023
4,CUST1296,Amy Johnson,Female,Teenagers,23-03-2021,Brazil,PROD105,Adidas Running Shoes,Apparel,1,110,ORD10004,02-07-2023,Returned,Cash on Delivery,1,very good,REV20004,18-10-2023

In [9]:
# Define the date columns to convert
date_columns = ['signup_date', 'order_date', 'review_date']

# Convert date columns to datetime objects with a specific format
for col in date_columns:
    # Using errors='coerce' will turn unparseable dates into NaT
    df[col] = pd.to_datetime(df[col], format='%d-%m-%Y', errors='coerce')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     10000 non-null  object
 1   full_name       10000 non-null  object
 2   gender          10000 non-null  object
 3   age_group       10000 non-null  object
 4   signup_date     10000 non-null  datetime64[ns]
 5   country         10000 non-null  object
 6   product_id      10000 non-null  object
 7   product_name    10000 non-null  object
 8   category        10000 non-null  object
 9   quantity        10000 non-null  int64
 10  unit_price      10000 non-null  int64
 11  order_id        10000 non-null  object
 12  order_date      10000 non-null  datetime64[ns]
 13  order_status    10000 non-null  object
 14  payment_method  10000 non-null  object
 15  rating          10000 non-null  int64
 16  review_text     10000 non-null  object
 17  review_id       10000 non-null  object
 18  review_date     10000 non-null  datetime64[ns]
dtypes: datetime64[ns](3), int64(3), object(13)
memory usage: 1.4+ MB

In [10]:
df["total_amount"] = df["quantity"] * df["unit_price"]
columns = df.columns.tolist()
columns.insert(11, columns.pop(columns.index('total_amount'))) # Move 'full_name' after 'customer_id'
df = df[columns]
display(df.head())

,customer_id,full_name,gender,age_group,signup_date,country,product_id,product_name,category,quantity,unit_price,total_amount,order_id,order_date,order_status,payment_method,rating,review_text,review_id,review_date
0,CUST2353,Erica Oliver,Female,Teenagers,2022-06-29,Canada,PROD108,Fitbit Versa 3,Electronics,3,229,687,ORD10000,2023-07-13,Pending,Credit Card,2,good,REV20000,2025-06-06
1,CUST4463,Christopher White,Male,Adults,2023-08-24,China,PROD103,Levi's Jeans,Apparel,4,59,236,ORD10001,2024-08-12,Pending,PayPal,2,average,REV20001,2023-08-05
2,CUST4512,Spencer Foster,Male,Senior,2023-07-18,Germany,PROD111,Lego Star Wars Set,Toys,2,59,118,ORD10002,2024-08-04,Delivered,Cash on Delivery,5,good,REV20002,2023-01-03
3,CUST5711,Jessica Harris,Male,Teenagers,2025-08-22,France,PROD107,Dyson Vacuum,Home & Kitchen,4,399,1596,ORD10003,2025-05-23,Delivered,Cash on Delivery,2,very good,REV20003,2023-03-14
4,CUST1296,Amy Johnson,Female,Teenagers,2021-03-23,Brazil,PROD105,Adidas Running Shoes,Apparel,1,110,110,ORD10004,2023-07-02,Returned,Cash on Delivery,1,very good,REV20004,2023-10-18

In [11]:
df.columns

Index(['customer_id', 'full_name', 'gender', 'age_group', 'signup_date',
       'country', 'product_id', 'product_name', 'category', 'quantity',
       'unit_price', 'total_amount', 'order_id', 'order_date', 'order_status',
       'payment_method', 'rating', 'review_text', 'review_id', 'review_date'],
      dtype='object')

In [12]:
df.to_csv('ecommerce_data_cleaned.csv', index=False)
print('Cleaned data saved to ecommerce_data_cleaned.csv')

Cleaned data saved to ecommerce_data_cleaned.csv